/*

DESCRIÇÃO:

 TODOS OS ANIMAIS ESTÃO TENDO UMA FESTA! CADA ANIMAL ESTÁ TRAZENDO UM PRATO. A REGRA É ÚNICA: O PRATO DEVE COMEÇAR E TERMINAR COM AS MESMAS LETRAS DO NOME DO ANIMAL. POR EXEMPLO, A GRANDE GARÇA AZUL ESTÁ TRAZENDO ALHO NAAN E O CHAPIM ESTÁ TRAZENDO BOLO DE CHOCOLATE.

 ESCREVA UMA FUNÇÃO BANQUETE QUE RECEBA O NOME E O PRATO DO ANIMAL COMO ARGUMENTOS E RETORNE VERDADEIRO OU FALSO PARA INDICAR SE O ANIMAL PODE TRAZER O PRATO PARA O BANQUETE.

 SUPONHA QUE BESTA E PRATO SEJAM SEMPRE STRINGS EM LETRAS MINÚSCULAS E QUE CADA UMA TENHA PELO MENOS DUAS LETRAS. BESTA E PRATO PODEM CONTER HÍFENS E ESPAÇOS, MAS ESTES NÃO APARECERÃO NO INÍCIO OU NO FINAL DA STRING. ELES NÃO CONTERÃO NUMERAIS.


*/

// beast = fera | animal
// dish = prato

function feast(beast, dish) {
  console.log({
    beast,
    dish,
  });
}

feast('great blue heron','garlic naan')
