/*
NESTE DESAFIO, VOCÊ DEVERÁ CALCULAR E IMPRIMIR A SOMA DOS ELEMENTOS DE UM ARRAY, LEMBRANDO QUE ALGUNS DESSES NÚMEROS INTEIROS PODEM SER BEM GRANDES.

DESCRIÇÃO DA FUNÇÃO

COMPLETE A FUNÇÃO AVERYBIGSUM NO EDITOR ABAIXO. DEVE RETORNAR A SOMA DE TODOS OS ELEMENTOS DO ARRAY.

AVERYBIGSUM TEM OS SEGUINTES PARÂMETROS:

INT AR[N] : UMA MATRIZ DE INTEIROS.
RETORNAR

LONG : A SOMA DE TODOS OS ELEMENTOS DO ARRAY
FORMATO DE ENTRADA

A PRIMEIRA LINHA DA ENTRADA CONSISTE EM UM NÚMERO INTEIRO.
A PRÓXIMA LINHA CONTÉMINTEIROS SEPARADOS POR ESPAÇO CONTIDOS NA MATRIZ.

FORMATO DE SAÍDA

RETORNE A SOMA INTEIRA DOS ELEMENTOS DO ARRAY.

*/

const bigNumber = [1000000001,1000000002 ,1000000003, 1000000004 ,1000000005]

function aVeryBigSum(ar) {
  // Write your code here
  const somaBig = ar.reduce((acc,item) =>  acc += item,0)

  return somaBig;
}


console.log('retorno função:',aVeryBigSum(bigNumber))